name: 'Setup Android Build Environment'
description: 'Sets up JDK, Gradle cache, and keystore for Android builds'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Cache gradle
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Create keystore.properties
      shell: bash
      run: touch keystore.properties