name: Test/Build Android

on:
  pull_request:
    branches: [master]
  push:
    # branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Android Build Environment
        uses: ./.github/actions/setup-android

      - name: Linter (gradle)
        run: ./gradlew ktlintCheck

      - name: Test (gradle)
        run: ./gradlew test --no-daemon

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

      - name: Build Debug APK
        uses: ./.github/actions/build-android-assets
        with:
          flavor: free
          build-type: apk
          build-variant: debug
          upload-target: artifact
          artifact-name: Debug APK

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Build Reports
          path: app/build/reports


