name: Create Release Assets

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
    
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: ${{ contains(github.ref_name, '-pre') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
          body: |
            # Amber Release ${{ github.ref_name }}
            
            Assets are being built and will be available shortly.
            
            ## Verification
            All release assets are signed with GPG key: `C00C563A025C327C95DF036AEE1FA70568414E2A`
            See [VERIFY_RELEASES.md](VERIFY_RELEASES.md) for verification instructions.

  build-apks:
    name: Build All APKs
    runs-on: ubuntu-latest
    needs: [create-release]
    outputs:
      manifest-entries: ${{ steps.build-apks.outputs.manifest-entries }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Android Build Environment
        uses: ./.github/actions/setup-android
        
      - name: Build All Release APKs
        id: build-apks
        uses: ./.github/actions/build-android-assets
        with:
          build-type: apk
          build-variant: release
          upload-target: release
          release-tag: ${{ github.ref_name }}
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-aabs:
    name: Build All AABs
    runs-on: ubuntu-latest
    needs: [create-release]
    outputs:
      manifest-entries: ${{ steps.build-aabs.outputs.manifest-entries }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Android Build Environment
        uses: ./.github/actions/setup-android
        
      - name: Build All Release AABs
        id: build-aabs
        uses: ./.github/actions/build-android-assets
        with:
          build-type: aab
          build-variant: release
          upload-target: release
          release-tag: ${{ github.ref_name }}
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finalize-release:
    name: Finalize Release
    runs-on: ubuntu-latest
    needs: [create-release, build-apks, build-aabs]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Finalize Release
        uses: ./.github/actions/finalize-release
        with:
          release-tag: ${{ github.ref_name }}
          manifest-data: |
            ${{ needs.build-apks.outputs.manifest-entries }}
            ${{ needs.build-aabs.outputs.manifest-entries }}
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}